<a href="https://colab.research.google.com/github/ednavivianasegura/Plan_de_Formacion_PDI_PAS_2026_privado/blob/main/02_pandas_ejercicios_solv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell" style="padding:1.5rem 0 2rem;">
  <div style="display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:1.5rem;padding-bottom:1.25rem;border-bottom:2px solid #1E3A8A;">
    <div style="flex:1;">
      <span style="display:inline-block;font-size:10px;font-weight:600;letter-spacing:1.2px;text-transform:uppercase;color:#0F766E;background:#CCFBF1;border:1px solid #5EEAD4;padding:3px 10px;border-radius:20px;margin-bottom:8px;">Plan de Formación PDI/PAS 2026</span>
      <div style="font-size:11px;color:#475569;letter-spacing:.6px;text-transform:uppercase;margin-bottom:6px;">Formación para la investigación</div>
      <div style="font-size:11px;font-style:italic;color:#475569;margin-bottom:4px;">Módulo 2 — Pandas · Ejercicios</div>
      <h1 style="font-size:24px;font-weight:700;color:#1E3A8A;line-height:1.2;margin:0;">Ejercicios Pandas — Soluciones</h1>
    </div>
    <div style="display:flex;flex-direction:column;align-items:center;gap:6px;flex-shrink:0;">
      <img src="https://github.com/ednavivianasegura/AccesoImages/blob/main/logoUR.png?raw=true" alt="Logo UR" style="width:72px;height:auto;">
      <div style="font-size:9px;font-weight:600;letter-spacing:.8px;text-transform:uppercase;color:#475569;text-align:center;line-height:1.4;">Universidad<br>de La Rioja</div>
    </div>
  </div>
  <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-bottom:14px;">
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-list-numbers" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Parte 1</div>
      <div style="font-size:12px;color:#1e293b;line-height:1.6;">10 ejercicios — Titanic: filtros, tipos, replace y apply</div>
    </div>
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-list-numbers" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Parte 2</div>
      <div style="font-size:12px;color:#1e293b;line-height:1.6;">26 ejercicios — Titanic: merge, groupby, map y transformaciones</div>
    </div>
    <div style="background:#fff;border:1px solid rgba(0,0,0,.1);border-radius:10px;padding:1rem;">
      <div style="font-size:10px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:#475569;margin-bottom:.7rem;padding-bottom:.5rem;border-bottom:1px solid rgba(0,0,0,.07);"><i class="ti ti-list-numbers" style="font-size:13px;color:#1E3A8A;vertical-align:-1px;"></i> &nbsp;Parte 3</div>
      <div style="font-size:12px;color:#1e293b;line-height:1.6;">10 ejercicios — Airbnb NYC: groupby, apply y rating</div>
    </div>
  </div>
  <div style="display:flex;align-items:center;justify-content:space-between;padding:9px 14px;background:#F8FAFF;border:1px solid #BFDBFE;border-radius:8px;font-size:11px;color:#94A3B8;">
    <span><i class="ti ti-school" style="font-size:12px;color:#1E3A8A;"></i> Universidad de La Rioja — Logroño, La Rioja</span>
    <span><i class="ti ti-calendar" style="font-size:12px;color:#1E3A8A;"></i> Plan de Formación PDI/PAS 2026</span>
  </div>
</div>

In [3]:
import numpy as np
import pandas as pd

In [8]:
!git clone https://github.com/ednavivianasegura/Curso_ML_Python.git

Cloning into 'Curso_ML_Python'...
remote: Enumerating objects: 1270, done.
remote: Counting objects: 100% (340/340), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 1270 (delta 317), reused 206 (delta 206), pack-reused 930 (from 1)
Receiving objects: 100% (1270/1270), 71.32 MiB | 20.71 MiB/s, done.
Resolving deltas: 100% (738/738), done.

In [9]:
import os
os.chdir("/content/Curso_ML_Python/Modulo1_b")

In [4]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell" style="padding:.8rem 0 .5rem;">
  <div style="display:flex;align-items:center;gap:12px;">
    <div style="width:4px;height:36px;background:#1E3A8A;border-radius:2px;flex-shrink:0;"></div>
    <div>
      <div style="font-size:17px;font-weight:600;color:#1E3A8A;">Parte 1 — Titanic</div>
      <div style="font-size:12px;color:#475569;margin-top:2px;">Filtros, tipos de datos, replace y apply</div>
    </div>
  </div>
  <hr class="nb-divider" style="margin-top:.8rem;">
</div>

In [6]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">0</div>
      <div>

        <div class="ex-title">Cargar el dataset</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Carga el archivo <code class='ic'>titanic.csv</code> y guárdalo en la variable <code class='ic'>df</code>.</p></div>
  </div>
  </div>

In [11]:
df = pd.read_csv("Data/titanic.csv")

df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1,PC 17599,71.2833
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250

In [12]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">1</div>
      <div>

        <div class="ex-title">Información del DataFrame</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Muestra la información del DataFrame.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.info()</code> muestra el tipo de dato de cada columna, los valores no nulos y el uso de memoria.</span></div>
</div>

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   Survived     891 non-null    int64
 5   Pclass       891 non-null    int64
 6   Ticket       891 non-null    object
 7   Fare         891 non-null    float64
dtypes: float64(2), int64(3), object(3)
memory usage: 55.8+ KB

In [14]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">2</div>
      <div>

        <div class="ex-title">Convertir columnas object a category</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Cambia las columnas del tipo <code class='ic'>object</code> a tipo <code class='ic'>category</code>.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>.astype('category')</code> sobre las columnas <code class='ic'>Name</code> y <code class='ic'>Sex</code>.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El tipo <code class='ic'>category</code> es más eficiente en memoria cuando una columna tiene pocos valores únicos repetidos.</span></div>
</div>

In [15]:
df[["Name", "Sex"]] = df[["Name", "Sex"]].astype("category")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    category
 2   Sex          891 non-null    category
 3   Age          714 non-null    float64
 4   Survived     891 non-null    int64
 5   Pclass       891 non-null    int64
 6   Ticket       891 non-null    object
 7   Fare         891 non-null    float64
dtypes: category(2), float64(2), int64(3), object(1)
memory usage: 83.9+ KB

In [17]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">3</div>
      <div>

        <div class="ex-title">Hombres</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén un DataFrame solo con hombres.</p></div>
  </div>

</div>

In [18]:
df[df["Sex"] == "male"]

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500
4,5,"Allen, Mr. William Henry",male,35.0,0,3,373450,8.0500
5,6,"Moran, Mr. James",male,NaN,0,3,330877,8.4583
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,1,17463,51.8625
7,8,"Palsson, Master. Gosta Leonard",male,2.0,0,3,349909,21.0750
...,...,...,...,...,...,...,...,...
883,884,"Banfield, Mr. Frederick James",male,28.0,0,2,C.A./SOTON 34068,10.5000
884,885,"Sutehall, Mr. Henry Jr",male,25.0,0,3,SOTON/OQ 392076,7.0500
886,887,"Montvila, Rev. Juozas",male,27.0,0,2,211536,13.0000
889,890,"Behr, Mr. Karl Howell",male,26.0,1,1,111369,30.0000
890,891,"Dooley, Mr. Patrick",male,32.0,0,3,370376,7.7500

In [19]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">4</div>
      <div>

        <div class="ex-title">Pasajeros de clase 1 y 2</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén un DataFrame con los pasajeros de clase 1 y 2.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>.isin([1, 2])</code> para filtrar varias clases a la vez.</span></div>
</div>

In [20]:
df[df["Pclass"].isin([1, 2])]

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1,PC 17599,71.2833
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,1,113803,53.1000
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,1,17463,51.8625
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,2,237736,30.0708
11,12,"Bonnell, Miss. Elizabeth",female,58.0,1,1,113783,26.5500
...,...,...,...,...,...,...,...,...
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,1,2,230433,26.0000
883,884,"Banfield, Mr. Frederick James",male,28.0,0,2,C.A./SOTON 34068,10.5000
886,887,"Montvila, Rev. Juozas",male,27.0,0,2,211536,13.0000
887,888,"Graham, Miss. Margaret Edith",female,19.0,1,1,112053,30.0000
889,890,"Behr, Mr. Karl Howell",male,26.0,1,1,111369,30.0000

In [21]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">5</div>
      <div>

        <div class="ex-title">Clase 1 y 3, menores de 30 años</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén un DataFrame con los pasajeros de la clase 1 y 3, menores a 30 años.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Combina <code class='ic'>.isin()</code> con un filtro de edad usando el operador <code class='ic'>&</code>.</span></div>
</div>

In [22]:
df[(df["Pclass"].isin([1, 3])) & (df["Age"] < 30)]

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250
7,8,"Palsson, Master. Gosta Leonard",male,2.0,0,3,349909,21.0750
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,1,3,347742,11.1333
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,3,PP 9549,16.7000
...,...,...,...,...,...,...,...,...
877,878,"Petroff, Mr. Nedelio",male,19.0,0,3,349212,7.8958
882,883,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,3,7552,10.5167
884,885,"Sutehall, Mr. Henry Jr",male,25.0,0,3,SOTON/OQ 392076,7.0500
887,888,"Graham, Miss. Margaret Edith",female,19.0,1,1,112053,30.0000
889,890,"Behr, Mr. Karl Howell",male,26.0,1,1,111369,30.0000

In [23]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">6</div>
      <div>

        <div class="ex-title">Pasajeros entre 20 y 30 años</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén un DataFrame con los pasajeros entre 20 y 30 años.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.between(a, b)</code> incluye ambos extremos: equivale a <code class='ic'>Age >= 20 & Age <= 30</code>.</span></div>
</div>

In [24]:
df[df["Age"].between(20, 30)]

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,1,3,347742,11.1333
12,13,"Saundercock, Mr. William Henry",male,20.0,0,3,A/5. 2151,8.0500
23,24,"Sloper, Mr. William Thompson",male,28.0,1,1,113788,35.5000
...,...,...,...,...,...,...,...,...
882,883,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,3,7552,10.5167
883,884,"Banfield, Mr. Frederick James",male,28.0,0,2,C.A./SOTON 34068,10.5000
884,885,"Sutehall, Mr. Henry Jr",male,25.0,0,3,SOTON/OQ 392076,7.0500
886,887,"Montvila, Rev. Juozas",male,27.0,0,2,211536,13.0000
889,890,"Behr, Mr. Karl Howell",male,26.0,1,1,111369,30.0000

In [25]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">7</div>
      <div>

        <div class="ex-title">Menores de 25 y mayores de 50</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén un DataFrame con los pasajeros menores a 25 años y mayores a 50 años.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>~</code> para negar el rango: <code class='ic'>~df['Age'].between(25, 50)</code>.</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El operador <code class='ic'>~</code> invierte el booleano: selecciona lo que <strong>no</strong> está en el rango [25, 50].</span></div>
</div>

In [26]:
df[~df["Age"].between(25, 50)]

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500
5,6,"Moran, Mr. James",male,NaN,0,3,330877,8.4583
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,1,17463,51.8625
7,8,"Palsson, Master. Gosta Leonard",male,2.0,0,3,349909,21.0750
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,2,237736,30.0708
...,...,...,...,...,...,...,...,...
878,879,"Laleff, Mr. Kristo",male,NaN,0,3,349217,7.8958
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,1,1,11767,83.1583
882,883,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,3,7552,10.5167
887,888,"Graham, Miss. Margaret Edith",female,19.0,1,1,112053,30.0000
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0,3,W./C. 6607,23.4500

In [27]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">8</div>
      <div>

        <div class="ex-title">Reemplazar valores de sexo</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Reemplaza los valores de sexo: <code class='ic'>M</code> para male y <code class='ic'>F</code> para female.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">La columna <code class='ic'>Sex</code> es de tipo <code class='ic'>category</code> — usa <code class='ic'>.cat.rename_categories()</code> para evitar FutureWarning.</span></div>
</div>

In [28]:
# Opción A — usando cat.rename_categories (recomendado para columnas category)
df["Sex"] = df["Sex"].cat.rename_categories({"male": "M", "female": "F"})
df["Sex"].unique()

['M', 'F']
Categories (2, object): ['F', 'M']

In [29]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">9</div>
      <div>

        <div class="ex-title">Nombres en mayúsculas</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Convierte en mayúsculas todos los nombres de los pasajeros.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.apply(lambda x: x.upper())</code> aplica la función a cada elemento de la columna. Es equivalente a <code class='ic'>.map(lambda x: x.upper())</code>.</span></div>
</div>

In [30]:
df["Name"] = df["Name"].apply(lambda x: x.upper())
df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"BRAUND, MR. OWEN HARRIS",M,22.0,0,3,A/5 21171,7.2500
1,2,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",F,38.0,1,1,PC 17599,71.2833
2,3,"HEIKKINEN, MISS. LAINA",F,26.0,1,3,STON/O2. 3101282,7.9250

In [31]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell" style="padding:.8rem 0 .5rem;">
  <div style="display:flex;align-items:center;gap:12px;">
    <div style="width:4px;height:36px;background:#1E3A8A;border-radius:2px;flex-shrink:0;"></div>
    <div>
      <div style="font-size:17px;font-weight:600;color:#1E3A8A;">Parte 2 — Titanic avanzado</div>
      <div style="font-size:12px;color:#475569;margin-top:2px;">Merge, groupby, transformaciones y análisis</div>
    </div>
  </div>
  <hr class="nb-divider" style="margin-top:.8rem;">
</div>

In [32]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">0</div>
      <div>

        <div class="ex-title">Cargar y combinar los datasets</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Carga ambos archivos <code class='ic'>titanic_1.csv</code> y <code class='ic'>titanic_2.csv</code> y guárdalos en <code class='ic'>df1</code> y <code class='ic'>df2</code> respectivamente.</p></div>
  </div>

</div>

In [36]:
df1 = pd.read_csv("Data/titanic_1.csv")
df2 = pd.read_csv("Data/titanic_2.csv")

In [33]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">1</div>
      <div>

        <div class="ex-title">Estadísticas descriptivas</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Muestra las estadísticas de cada uno de los DataFrames.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.describe()</code> devuelve count, mean, std, min, 25%, 50%, 75% y max para columnas numéricas.</span></div>
</div>

In [37]:
df1.describe()

       PassengerId         Age
count   891.000000  714.000000
mean    446.000000   29.699118
std     257.353842   14.526497
min       1.000000    0.420000
25%     223.500000   20.125000
50%     446.000000   28.000000
75%     668.500000   38.000000
max     891.000000   80.000000

In [38]:
df2.describe()

       PassengerId    Survived      Pclass        Fare
count   891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   32.204208
std     257.353842    0.486592    0.836071   49.693429
min       1.000000    0.000000    1.000000    0.000000
25%     223.500000    0.000000    2.000000    7.910400
50%     446.000000    0.000000    3.000000   14.454200
75%     668.500000    1.000000    3.000000   31.000000
max     891.000000    1.000000    3.000000  512.329200

In [39]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">2</div>
      <div>

        <div class="ex-title">Unir los DataFrames</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Une los DataFrames para obtener solo uno.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>pd.merge()</code> con <code class='ic'>on='PassengerId'</code> y <code class='ic'>how='inner'</code> para conservar solo los pasajeros presentes en ambos.</span></div>
</div>

In [40]:
df = pd.merge(left = df1, right = df2, left_on = "PassengerId", right_on = "PassengerId", how = "inner")

df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1,PC 17599,71.2833
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250

In [41]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">3</div>
      <div>

        <div class="ex-title">Últimas 5 filas de Name y Age</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Imprime las últimas 5 filas de las columnas de nombre y edad.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.head(5)</code> devuelve las primeras 5 filas. Para las últimas 5 se usa <code class='ic'>.tail(5)</code>.</span></div>
</div>

In [43]:
df[["Name", "Age"]].head(5)

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

In [42]:
df[["Name", "Age"]].tail(5)

                                         Name   Age
886                     Montvila, Rev. Juozas  27.0
887              Graham, Miss. Margaret Edith  19.0
888  Johnston, Miss. Catherine Helen "Carrie"   NaN
889                     Behr, Mr. Karl Howell  26.0
890                       Dooley, Mr. Patrick  32.0

In [44]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">4</div>
      <div>

        <div class="ex-title">Primeras 10 pasajeras femeninas</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Imprime las primeras 10 filas de las instancias que en sexo sean igual a femenino.</p></div>
  </div>

</div>

In [45]:
df[df["Sex"] == "female"].head(10)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1,PC 17599,71.2833
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,1,113803,53.1000
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,1,3,347742,11.1333
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,2,237736,30.0708
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,3,PP 9549,16.7000
11,12,"Bonnell, Miss. Elizabeth",female,58.0,1,1,113783,26.5500
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,3,350406,7.8542
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,1,2,248706,16.0000
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,0,3,345763,18.0000

In [46]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">5</div>
      <div>

        <div class="ex-title">Fare < 33 y Pclass == 2</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Imprime las instancias que en la columna <code class='ic'>Fare</code> sean menor a 33 y en la columna <code class='ic'>Pclass</code> igual a 2.</p></div>
  </div>

</div>

In [47]:
df_ej5 = df[(df["Fare"] < 33) & (df["Pclass"] == 2)]
df_ej5.head(10)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,2,237736,30.0708
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,1,2,248706,16.0000
17,18,"Williams, Mr. Charles Eugene",male,NaN,1,2,244373,13.0000
20,21,"Fynney, Mr. Joseph J",male,35.0,0,2,239865,26.0000
21,22,"Beesley, Mr. Lawrence",male,34.0,1,2,248698,13.0000
33,34,"Wheadon, Mr. Edward H",male,66.0,0,2,C.A. 24579,10.5000
41,42,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,0,2,11668,21.0000
53,54,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...",female,29.0,1,2,2926,26.0000
56,57,"Rugg, Miss. Emily",female,21.0,1,2,C.A. 31026,10.5000
58,59,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500

In [48]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">6</div>
      <div>

        <div class="ex-title">Número de hombres y mujeres del resultado anterior</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Del resultado anterior obtén el número de hombres y el número de mujeres.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.value_counts(dropna=False)</code> incluye los NaN en el conteo. <code class='ic'>normalize=True</code> muestra frecuencias relativas.</span></div>
</div>

In [49]:
df_ej5["Sex"].value_counts(dropna=False)

Sex
male      95
female    68
Name: count, dtype: int64

In [50]:
df_ej5["Sex"].value_counts(dropna=False, normalize=True)

Sex
male      0.582822
female    0.417178
Name: proportion, dtype: float64

In [51]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">7</div>
      <div>

        <div class="ex-title">Coste total de tickets por sexo</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén el coste total de los tickets de hombres y el coste total de los tickets de mujeres.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">La versión con <code class='ic'>groupby</code> es más compacta y eficiente que filtrar dos veces.</span></div>
</div>

In [52]:
df[df["Sex"] == "female"]["Fare"].sum()

np.float64(13966.6628)

In [53]:
df[df["Sex"] == "male"]["Fare"].sum()

np.float64(14727.286500000002)

In [54]:
df.groupby("Sex")["Fare"].sum()

Sex
female    13966.6628
male      14727.2865
Name: Fare, dtype: float64

In [55]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">8</div>
      <div>

        <div class="ex-title">Coste total y número de pasajeros por clase</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén el coste total de los tickets por cada clase (1, 2 y 3) y el número de pasajeros de cada clase.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>size</code> en <code class='ic'>.agg()</code> cuenta todas las filas del grupo incluyendo NaN, a diferencia de <code class='ic'>count</code>.</span></div>
</div>

In [56]:
# Para la clase 1

print("Total Ticket:", df[df["Pclass"] == 1]["Fare"].sum())
print("Total Pasajeros:", df[df["Pclass"] == 1].shape[0])

Total Ticket: 18177.4125
Total Pasajeros: 216

In [57]:
# Para la clase 2

print("Total Ticket:", df[df["Pclass"] == 2]["Fare"].sum())
print("Total Pasajeros:", df[df["Pclass"] == 2].shape[0])

Total Ticket: 3801.8417
Total Pasajeros: 184

In [58]:
# Para la clase 3

print("Total Ticket:", df[df["Pclass"] == 3]["Fare"].sum())
print("Total Pasajeros:", df[df["Pclass"] == 3].shape[0])

Total Ticket: 6714.6951
Total Pasajeros: 491

In [59]:
df.groupby("Pclass").agg({"Fare" : ["sum", "size"]})

              Fare
               sum size
Pclass
1       18177.4125  216
2        3801.8417  184
3        6714.6951  491

In [60]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">9</div>
      <div>

        <div class="ex-title">Columna con el apellido</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Crea una columna con el apellido de cada pasajero y agrégala al DataFrame.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">El nombre tiene formato <code class='ic'>Apellido, Título Nombre</code>. Usa <code class='ic'>.split(',')[0]</code> para extraer el apellido.</span></div>
</div>

In [61]:
df["Surname"] = df["Name"].apply(lambda x: x.split(",")[0])
df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500,Braund
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1,PC 17599,71.2833,Cumings
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250,Heikkinen

In [62]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">10</div>
      <div>

        <div class="ex-title">Apellidos repetidos</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra si se repiten apellidos en la columna creada en el ejercicio anterior. Usa <code class='ic'>.value_counts()</code>.</p></div>
  </div>

</div>

In [63]:
df["Surname"].value_counts()

Surname
Andersson    9
Sage         7
Skoog        6
Panula       6
Carter       6
            ..
Nysveen      1
Young        1
Slayter      1
Danoff       1
Haas         1
Name: count, Length: 667, dtype: int64

In [64]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">11</div>
      <div>

        <div class="ex-title">Apellidos que aparecen más de una vez</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra los apellidos que se repiten. Es decir, muestra solo los apellidos que aparecen más de 1 vez.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>.duplicated()</code> marca como <code class='ic'>True</code> las repeticiones (no la primera aparición). <code class='ic'>.unique()</code> elimina los duplicados del resultado.</span></div>
</div>

In [65]:
df[df["Surname"].duplicated()]["Surname"].unique()

array(['Palsson', 'Vander Planke', 'Andersson', 'Goodwin', 'Fortune',
       'Moran', 'Turpin', 'Nasser', 'White', 'Nicola-Yarred', 'Futrelle',
       'Ford', 'Williams', 'Panula', 'Skoog', 'Rice', 'Johnson', 'Sage',
       'Asplund', 'Navratil', 'Olsen', 'Backstrom', 'Harris', 'Lefebre',
       'Zabour', 'Attalah', 'Strom', 'Smith', 'Baxter', 'Allison',
       'Kantor', 'Caldwell', 'Goldsmith', 'McCoy', 'Graham', 'Pears',
       'Brown', 'Arnold-Franchi', "O'Brien", 'Meyer', 'Gustafsson',
       'Holverson', 'Carter', 'Newell', 'Sandstrom', 'Johansson',
       'Olsson', 'Jussila', 'Hakkarainen', 'Hart', 'Minahan', 'Rosblom',
       'Richards', 'Mellinger', 'West', 'Baclini', 'Braund', 'Bishop',
       'Hoyt', 'Coutts', 'Hagland', 'Calic', 'Penasco y Castellana',
       'Webber', 'Hippach', 'Quick', 'Elias', 'Peter', 'Cacic', 'Beane',
       'Davies', 'Taussig', 'Flynn', 'Kelly', 'Silvey', 'Thayer',
       'Bourke', 'Van Impe', 'Boulos', 'Duff Gordon', 'Jacobsohn',
       'Laroche', 'Murphy', 'Danbom', 'Lobb', 'Becker', 'Nakid',
       'Collyer', 'Thorneycroft', 'Harper', 'Stanley', 'Doling',
       'Hickman', 'Frauenthal', 'Coleff', 'Chapman', 'Barbara', 'Hansen',
       'Morley', 'Moubarek', 'Taylor', 'Larsson', 'Jensen', 'Oreskovic',
       'Renouf', 'Allen', 'Ryerson', 'Crosby', 'Abbott', 'Herman',
       'Hamalainen', 'Hocking', 'Dick', 'Ali', 'Dean', 'Keane', 'Andrews',
       'Chambers', 'Hays', 'Moor', 'Lam', 'Mallet', 'Yasbeck', 'Saad',
       'Goldenberg', 'Svensson', 'Wick', 'Daly', 'Beckwith', 'Carlsson',
       'Abelson', 'Petroff', 'Johnston'], dtype=object)

In [66]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">12</div>
      <div>

        <div class="ex-title">Pasajeros con PassengerID múltiplo de 3</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Imprime los primeros 10 pasajeros que tengan un <code class='ic'>PassengerID</code> múltiplo de 3.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>df.iloc[range(2, 31, 3), :]</code> — los múltiplos de 3 tienen índice 2, 5, 8… (index base 0).</span></div><div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Alternativa más clara: <code class='ic'>df[df['PassengerId'] % 3 == 0].head(10)</code></span></div>
</div>

In [67]:
# Opción A — iloc con range
df.iloc[range(2, 31, 3), :]

# Opción B — filtro módulo (más legible)
# df[df["PassengerId"] % 3 == 0].head(10)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250,Heikkinen
5,6,"Moran, Mr. James",male,NaN,0,3,330877,8.4583,Moran
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,1,3,347742,11.1333,Johnson
11,12,"Bonnell, Miss. Elizabeth",female,58.0,1,1,113783,26.5500,Bonnell
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,3,350406,7.8542,Vestrom
17,18,"Williams, Mr. Charles Eugene",male,NaN,1,2,244373,13.0000,Williams
20,21,"Fynney, Mr. Joseph J",male,35.0,0,2,239865,26.0000,Fynney
23,24,"Sloper, Mr. William Thompson",male,28.0,1,1,113788,35.5000,Sloper
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,3,2631,7.2250,Emir
29,30,"Todoroff, Mr. Lalio",male,NaN,0,3,349216,7.8958,Todoroff

In [68]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">13</div>
      <div>

        <div class="ex-title">Apellidos de mujeres menores de 20 años</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ ¿Cuáles son los apellidos de los pasajeros que son mujeres y menores de 20 años?</p></div>
  </div>

</div>

In [69]:
apellidos_mujeres = df[(df["Sex"] == "female") & (df["Age"] < 20)]["Surname"].to_list()
print(apellidos_mujeres)

['Nasser', 'Sandstrom', 'Vestrom', 'McGowan', 'Palsson', 'Vander Planke', 'Nicola-Yarred', 'Laroche', 'Devaney', 'Arnold-Franchi', 'West', 'Andersson', 'Goodwin', 'Ilett', 'Zabour', 'Attalah', 'Andersson', 'Newsom', 'Ford', 'Gilnagh', 'Johnson', 'Kink-Heilmann', 'Andersen-Jensen', 'Strom', 'Carr', 'Asplund', 'Collyer', 'Bishop', 'Allison', 'Penasco y Castellana', 'Ryerson', 'Hippach', 'Palsson', 'Nakid', 'Lehmann', 'Silven', 'Van Impe', 'Phillips', 'Carter', 'Mellinger', 'Baclini', 'Baclini', 'Hirvonen', 'Maioni', 'Quick', 'Hart', 'Andersson', 'Andersson', 'Beane', 'Taussig', 'Becker', 'Skoog', 'Skoog', 'Baclini', 'Doling', 'Hegarty', 'Turja', 'Madill', 'Karun', 'Astor', 'Barbara', 'Harper', 'Wells', 'Emanuel', 'Ayoub', 'Dick', 'Sjoblom', 'Pettersson', 'Andersson', 'Yasbeck', 'Boulos', 'Lines', 'Aks', 'Najib', 'Graham']

In [70]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">14</div>
      <div>

        <div class="ex-title">Apellidos de hombres mayores de 45 años</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ ¿Cuáles son los apellidos de los pasajeros que son hombres y mayores de 45 años?</p></div>
  </div>

</div>

In [71]:
apellidos_hombres = df[(df["Sex"] == "male") & (df["Age"] > 45)]["Surname"].to_list()
print(apellidos_hombres)

['McCarthy', 'Wheadon', 'Ostby', 'Chaffee', 'Coxon', 'Goldschmidt', 'Porter', 'Connors', 'White', 'Bateman', 'Meo', 'Williams', 'Van der hoef', 'Smith', 'Youseff', 'Green', 'Sjostedt', 'Carter', 'Stead', 'Taussig', 'Duane', 'Moraweck', 'Nysveen', 'Partner', 'McKane', 'Widegren', 'Silvey', 'Fortune', 'Peuchen', 'Goldenberg', 'Millet', 'Anderson', 'Gee', 'Milling', 'Smart', 'Rouse', 'Kent', 'Molson', 'Artagaveytia', 'Walker', 'Douglas', 'Nicholson', 'Wright', 'Harris', 'Downton', 'Jarvis', 'Frolicher-Stehli', 'Elsbury', 'Johnson', 'Duff Gordon', 'Sutton', 'Kirkland', 'Barkworth', 'Lundahl', 'Harper', 'Simonius-Blumer', 'Newell', 'Frauenthal', 'Colley', 'Mitchell', 'Brown', 'Weir', 'Chapman', 'Thayer', 'Taylor', 'Greenberg', 'Hodges', 'Crosby', 'Jensen', 'Guggenheim', 'Svensson', 'Daly', 'Vander Cruyssen']

In [72]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">15</div>
      <div>

        <div class="ex-title">Apellidos en común</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Compara si coinciden los apellidos generados en los ejercicios anteriores.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>set.intersection()</code> devuelve los elementos presentes en ambos conjuntos. Es la forma más eficiente de encontrar coincidencias entre dos listas.</span></div>
</div>

In [74]:
apellidos_hombres_set = set(apellidos_hombres)

apellidos_mujeres_set = set(apellidos_mujeres)


apellidos_hombres_set.intersection(apellidos_mujeres_set)

{'Carter', 'Harper', 'Johnson', 'Taussig'}

In [75]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">16</div>
      <div>

        <div class="ex-title">10 no supervivientes más jóvenes por sexo</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra los 10 pasajeros que no sobrevivieron más jóvenes e imprime cuántos son hombres y cuántos son mujeres.</p></div>
  </div>

</div>

In [76]:
df[df["Survived"] == 0].sort_values("Age").head(10)["Sex"].value_counts()

Sex
male      5
female    5
Name: count, dtype: int64

In [77]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">17</div>
      <div>

        <div class="ex-title">3 supervivientes por sexo y clase</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ En un DataFrame muestra 3 pasajeros que sean hombres y 3 que sean mujeres, que hayan sobrevivido y para cada clase de la columna <code class='ic'>Pclass</code>.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El bucle itera sobre todas las combinaciones de sexo y clase, concatenando los resultados con <code class='ic'>pd.concat()</code>.</span></div>
</div>

In [78]:
df_17 = pd.DataFrame()
for sex in df["Sex"].unique():
    for pclass in df["Pclass"].unique():
        df_ = df[(df["Sex"] == sex) & (df["Pclass"] == pclass) & (df["Survived"] == 1)].head(3)
        df_17 = pd.concat([df_17, df_], axis=0, ignore_index=True)
df_17

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname
0,37,"Mamee, Mr. Hanna",male,NaN,1,3,2677,7.2292,Mamee
1,66,"Moubarek, Master. Gerios",male,NaN,1,3,2661,15.2458,Moubarek
2,75,"Bing, Mr. Lee",male,32.00,1,3,1601,56.4958,Bing
3,24,"Sloper, Mr. William Thompson",male,28.00,1,1,113788,35.5000,Sloper
4,56,"Woolner, Mr. Hugh",male,NaN,1,1,19947,35.5000,Woolner
5,98,"Greenfield, Mr. William Bertram",male,23.00,1,1,PC 17759,63.3583,Greenfield
6,18,"Williams, Mr. Charles Eugene",male,NaN,1,2,244373,13.0000,Williams
7,22,"Beesley, Mr. Lawrence",male,34.00,1,2,248698,13.0000,Beesley
8,79,"Caldwell, Master. Alden Gates",male,0.83,1,2,248738,29.0000,Caldwell
9,3,"Heikkinen, Miss. Laina",female,26.00,1,3,STON/O2. 3101282,7.9250,Heikkinen
10,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,1,3,347742,11.1333,Johnson
11,11,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,3,PP 9549,16.7000,Sandstrom
12,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.00,1,1,PC 17599,71.2833,Cumings
13,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,1,113803,53.1000,Futrelle
14,12,"Bonnell, Miss. Elizabeth",female,58.00,1,1,113783,26.5500,Bonnell
15,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,2,237736,30.0708,Nasser
16,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,1,2,248706,16.0000,Hewlett
17,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,Laroche

In [79]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">18</div>
      <div>

        <div class="ex-title">Convertir int64 a int32</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Obtén el tipo de elementos de cada columna y convierte los que sean <code class='ic'>int64</code> a <code class='ic'>int32</code>. Evalúa la memoria antes y después.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>int32</code> usa la mitad de memoria que <code class='ic'>int64</code> (4 bytes vs 8 bytes por elemento). En datasets grandes esto puede reducir significativamente el uso de RAM.</span></div>
</div>

In [80]:
print("--- Antes ---")
df.info()

datos_columnas = df.dtypes.to_dict()

datos_columnas

--- Antes ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   Survived     891 non-null    int64
 5   Pclass       891 non-null    int64
 6   Ticket       891 non-null    object
 7   Fare         891 non-null    float64
 8   Surname      891 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 62.8+ KB

{'PassengerId': dtype('int64'),
 'Name': dtype('O'),
 'Sex': dtype('O'),
 'Age': dtype('float64'),
 'Survived': dtype('int64'),
 'Pclass': dtype('int64'),
 'Ticket': dtype('O'),
 'Fare': dtype('float64'),
 'Surname': dtype('O')}

In [81]:

print("\n--- Después ---")

for llave, valor in datos_columnas.items():
    if valor == "int64":
        df[llave] = df[llave].astype("int32")

df.info()

--- Después ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int32
 1   Name         891 non-null    object
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   Survived     891 non-null    int32
 5   Pclass       891 non-null    int32
 6   Ticket       891 non-null    object
 7   Fare         891 non-null    float64
 8   Surname      891 non-null    object
dtypes: float64(2), int32(3), object(4)
memory usage: 52.3+ KB

In [82]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">19</div>
      <div>

        <div class="ex-title">Clase 1 y 3 entre 20 y 25 años</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra a los pasajeros de la clase 1 y 3 entre 20 y 25 años y comprueba si son más hombres o mujeres.</p></div>
  </div>

</div>

In [83]:
df[(df["Pclass"].isin([1, 3])) & (df["Age"].between(20, 25))]["Sex"].value_counts()

Sex
male      73
female    34
Name: count, dtype: int64

In [84]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">20</div>
      <div>

        <div class="ex-title">Columna Rango edad</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Agrega una nueva columna <code class='ic'>rango_edad</code> que categorice así:</p><p class="ex-task">→ Niño &lt; 11 años · Joven &lt; 18 años · Adulto &lt; 50 años · Mayor ≥ 50 años</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">La función <code class='ic'>rango_edad()</code> se aplica a cada elemento de <code class='ic'>Age</code> con <code class='ic'>.apply()</code>. Los NaN devolverán un error — ver ejercicio 22 para su tratamiento.</span></div>
</div>

In [86]:
def rango_edad(edad):
    if edad < 11:  return "niño"
    elif edad < 18: return "joven"
    elif edad < 50: return "adulto"
    else:           return "mayor"

In [87]:
df["rango_edad"] = df["Age"].apply(lambda x: rango_edad(x))
df.head(10)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad
0,1,"Braund, Mr. Owen Harris",male,22.0,0,3,A/5 21171,7.2500,Braund,adulto
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,1,PC 17599,71.2833,Cumings,adulto
2,3,"Heikkinen, Miss. Laina",female,26.0,1,3,STON/O2. 3101282,7.9250,Heikkinen,adulto
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,1,113803,53.1000,Futrelle,adulto
4,5,"Allen, Mr. William Henry",male,35.0,0,3,373450,8.0500,Allen,adulto
5,6,"Moran, Mr. James",male,NaN,0,3,330877,8.4583,Moran,mayor
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,1,17463,51.8625,McCarthy,mayor
7,8,"Palsson, Master. Gosta Leonard",male,2.0,0,3,349909,21.0750,Palsson,niño
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,1,3,347742,11.1333,Johnson,adulto
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,2,237736,30.0708,Nasser,joven

In [88]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">21</div>
      <div>

        <div class="ex-title">Jóvenes y mayores de clase 2 y 3 supervivientes</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra a los pasajeros <code class='ic'>joven</code> y <code class='ic'>mayor</code> de la clase 2 y 3 que hayan sobrevivido. Imprime los 10 primeros.</p></div>
  </div>

</div>

In [89]:
df[(df["rango_edad"].isin(["joven", "mayor"])) & (df["Pclass"].isin([2, 3])) & (df["Survived"] == 1)].head(10)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,2,237736,30.0708,Nasser,joven
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,1,2,248706,16.0000,Hewlett,mayor
17,18,"Williams, Mr. Charles Eugene",male,NaN,1,2,244373,13.0000,Williams,mayor
19,20,"Masselmani, Mrs. Fatima",female,NaN,1,3,2649,7.2250,Masselmani,mayor
22,23,"McGowan, Miss. Anna ""Annie""",female,15.0,1,3,330923,8.0292,McGowan,joven
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,1,3,330959,7.8792,O'Dwyer,mayor
32,33,"Glynn, Miss. Mary Agatha",female,NaN,1,3,335677,7.7500,Glynn,mayor
36,37,"Mamee, Mr. Hanna",male,NaN,1,3,2677,7.2292,Mamee,mayor
39,40,"Nicola-Yarred, Miss. Jamila",female,14.0,1,3,2651,11.2417,Nicola-Yarred,joven
47,48,"O'Driscoll, Miss. Bridget",female,NaN,1,3,14311,7.7500,O'Driscoll,mayor

In [90]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">22</div>
      <div>

        <div class="ex-title">Rellenar NaN con la edad promedio</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra la edad promedio de todos los pasajeros y reemplázala por los NaN en la columna <code class='ic'>Age</code>. Ejecuta el ejercicio anterior.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Rellenar NaN con la media es una técnica común de <strong>imputación de datos</strong>. Alternativas más sofisticadas incluyen la mediana o modelos predictivos.</span></div>
</div>

In [91]:
edad_promedio = df["Age"].mean()
print("Edad promedio:", round(edad_promedio, 2))

Edad promedio: 29.7

In [93]:
# Usar esto:
df["Age"] = df["Age"].fillna(edad_promedio)

df.head(10)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad
0,1,"Braund, Mr. Owen Harris",male,22.000000,0,3,A/5 21171,7.2500,Braund,adulto
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,1,PC 17599,71.2833,Cumings,adulto
2,3,"Heikkinen, Miss. Laina",female,26.000000,1,3,STON/O2. 3101282,7.9250,Heikkinen,adulto
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,1,113803,53.1000,Futrelle,adulto
4,5,"Allen, Mr. William Henry",male,35.000000,0,3,373450,8.0500,Allen,adulto
5,6,"Moran, Mr. James",male,29.699118,0,3,330877,8.4583,Moran,mayor
6,7,"McCarthy, Mr. Timothy J",male,54.000000,0,1,17463,51.8625,McCarthy,mayor
7,8,"Palsson, Master. Gosta Leonard",male,2.000000,0,3,349909,21.0750,Palsson,niño
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,1,3,347742,11.1333,Johnson,adulto
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,2,237736,30.0708,Nasser,joven

In [94]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">23</div>
      <div>

        <div class="ex-title">Traducir columna Sex al español</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Cambia a español la columna <code class='ic'>Sex</code>.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Si la columna es de tipo <code class='ic'>category</code>, usa <code class='ic'>.cat.rename_categories()</code> para evitar el FutureWarning.</span></div>
</div>

In [95]:
# Si la columna es object:
df["Sex"] = df["Sex"].replace({"male": "hombre", "female": "mujer"})
df["Sex"].unique()

array(['hombre', 'mujer'], dtype=object)

In [96]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">24</div>
      <div>

        <div class="ex-title">Columnas string a mayúsculas</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Convierte a mayúsculas todas las columnas cuyos valores sean cadenas de texto.</p></div>
  </div>
  <div class="hint-box"><i class="ti ti-bulb" style="color:#D97706;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="hint-text">Usa <code class='ic'>.dtypes.to_dict()</code> para iterar sobre los tipos y aplicar <code class='ic'>.upper()</code> solo a las columnas <code class='ic'>object</code>.</span></div>
</div>

In [97]:
datos_columnas = df.dtypes.to_dict()

datos_columnas

{'PassengerId': dtype('int32'),
 'Name': dtype('O'),
 'Sex': dtype('O'),
 'Age': dtype('float64'),
 'Survived': dtype('int32'),
 'Pclass': dtype('int32'),
 'Ticket': dtype('O'),
 'Fare': dtype('float64'),
 'Surname': dtype('O'),
 'rango_edad': dtype('O')}

In [98]:
for llave, valor in datos_columnas.items():
    if valor == "object":
        df[llave] = df[llave].apply(lambda x : x.upper())


df.head()

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad
0,1,"BRAUND, MR. OWEN HARRIS",HOMBRE,22.0,0,3,A/5 21171,7.2500,BRAUND,ADULTO
1,2,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",MUJER,38.0,1,1,PC 17599,71.2833,CUMINGS,ADULTO
2,3,"HEIKKINEN, MISS. LAINA",MUJER,26.0,1,3,STON/O2. 3101282,7.9250,HEIKKINEN,ADULTO
3,4,"FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)",MUJER,35.0,1,1,113803,53.1000,FUTRELLE,ADULTO
4,5,"ALLEN, MR. WILLIAM HENRY",HOMBRE,35.0,0,3,373450,8.0500,ALLEN,ADULTO

In [99]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">25</div>
      <div>

        <div class="ex-title">Edad promedio por sexo y rango</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Agrupa por sexo y rango de edad y encuentra la edad promedio.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Recuerda usar <code class='ic'>'mean'</code> como string para evitar el FutureWarning de pandas 3.x.</span></div>
</div>

In [100]:
df.groupby(["Sex", "rango_edad"]).agg({"Age": ["mean"]})

                         Age
                        mean
Sex    rango_edad
HOMBRE ADULTO      30.196793
       JOVEN       15.320000
       MAYOR       38.242560
       NIÑO         3.959697
MUJER  ADULTO      30.260870
       JOVEN       15.229167
       MAYOR       37.120710
       NIÑO         4.596774

In [101]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">26</div>
      <div>

        <div class="ex-title">Dividir columna Name</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Divide la columna <code class='ic'>Name</code> en: <code class='ic'>Mrs/Miss</code>, <code class='ic'>Apellido</code> y <code class='ic'>Nombre(s)</code>.</p><p class="ex-task">→ Nota: Ignora el resto de información.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El formato es: <code class='ic'>Apellido, Título Nombre</code>. El título se extrae con <code class='ic'>split(',')[1].split()[0]</code> y el nombre con <code class='ic'>split(',')[1].split()[1:]</code>.</span></div>
</div>

In [102]:
df["Mrs/Mss"] = df["Name"].apply(lambda x : x.split(",")[1].split()[0])

df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad,Mrs/Mss
0,1,"BRAUND, MR. OWEN HARRIS",HOMBRE,22.0,0,3,A/5 21171,7.2500,BRAUND,ADULTO,MR.
1,2,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",MUJER,38.0,1,1,PC 17599,71.2833,CUMINGS,ADULTO,MRS.
2,3,"HEIKKINEN, MISS. LAINA",MUJER,26.0,1,3,STON/O2. 3101282,7.9250,HEIKKINEN,ADULTO,MISS.

In [103]:
df["Apellido"] = df["Name"].apply(lambda x : x.split(",")[0])

df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad,Mrs/Mss,Apellido
0,1,"BRAUND, MR. OWEN HARRIS",HOMBRE,22.0,0,3,A/5 21171,7.2500,BRAUND,ADULTO,MR.,BRAUND
1,2,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",MUJER,38.0,1,1,PC 17599,71.2833,CUMINGS,ADULTO,MRS.,CUMINGS
2,3,"HEIKKINEN, MISS. LAINA",MUJER,26.0,1,3,STON/O2. 3101282,7.9250,HEIKKINEN,ADULTO,MISS.,HEIKKINEN

In [104]:
df["Nombre"] = df["Name"].apply(lambda x : " ".join(x.split(",")[1].split()[1:]))

df.head(3)

,PassengerId,Name,Sex,Age,Survived,Pclass,Ticket,Fare,Surname,rango_edad,Mrs/Mss,Apellido,Nombre
0,1,"BRAUND, MR. OWEN HARRIS",HOMBRE,22.0,0,3,A/5 21171,7.2500,BRAUND,ADULTO,MR.,BRAUND,OWEN HARRIS
1,2,"CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...",MUJER,38.0,1,1,PC 17599,71.2833,CUMINGS,ADULTO,MRS.,CUMINGS,JOHN BRADLEY (FLORENCE BRIGGS THAYER)
2,3,"HEIKKINEN, MISS. LAINA",MUJER,26.0,1,3,STON/O2. 3101282,7.9250,HEIKKINEN,ADULTO,MISS.,HEIKKINEN,LAINA

In [105]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell" style="padding:.8rem 0 .5rem;">
  <div style="display:flex;align-items:center;gap:12px;">
    <div style="width:4px;height:36px;background:#1E3A8A;border-radius:2px;flex-shrink:0;"></div>
    <div>
      <div style="font-size:17px;font-weight:600;color:#1E3A8A;">Parte 3 — Airbnb NYC</div>
      <div style="font-size:12px;color:#475569;margin-top:2px;">groupby, apply y cálculo de rating</div>
    </div>
  </div>
  <hr class="nb-divider" style="margin-top:.8rem;">
</div>

In [106]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">0</div>
      <div>

        <div class="ex-title">Cargar y unir los datasets de Airbnb</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Une los dos DataFrames por la columna <code class='ic'>id</code>. Guarda el nuevo DataFrame en <code class='ic'>df</code>.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text"><code class='ic'>pd.merge()</code> con <code class='ic'>how='inner'</code> (por defecto) conserva solo las filas con <code class='ic'>id</code> presente en ambos datasets.</span></div>
</div>

In [108]:
df1 = pd.read_excel("Data/Airbnb_NYC.xlsx", sheet_name="NYC1")
df2 = pd.read_excel("Data/Airbnb_NYC.xlsx", sheet_name="NYC2")
df = pd.merge(left=df2, right=df1, on="id")
print(df.shape)
df.head()

(48895, 16)

,id,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,name,host_id,host_name,municipio,barrio,latitude,longitude,room_type
0,2539.0,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room
1,2595.0,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt
2,3647.0,150.0,3.0,0.0,NaT,NaN,1.0,365.0,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room
3,3831.0,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt
4,5022.0,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  float64
 1   price                           48895 non-null  float64
 2   minimum_nights                  48895 non-null  float64
 3   number_of_reviews               48895 non-null  float64
 4   last_review                     38843 non-null  datetime64[ns]
 5   reviews_per_month               38843 non-null  float64
 6   calculated_host_listings_count  48895 non-null  float64
 7   availability_365                48895 non-null  float64
 8   name                            48870 non-null  object
 9   host_id                         48895 non-null  int64
 10  host_name                       48873 non-null  object
 11  municipio                       48895 non-null  object
 12  barrio                          48895 non-null  object
 13  latitude                        48895 non-null  float64
 14  longitude                       48895 non-null  float64
 15  room_type                       48895 non-null  object
dtypes: datetime64[ns](1), float64(9), int64(1), object(5)
memory usage: 6.0+ MB

In [110]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">1</div>
      <div>

        <div class="ex-title">Airbnb en Manhattan con más reviews</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Si quiero hospedarme en Manhattan una sola noche y para elegir el Airbnb me guío por el que tenga el mayor número de reviews, ¿dónde me debería hospedar?</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Se filtra por <code class='ic'>minimum_nights >= 1</code> (cualquier alojamiento acepta al menos 1 noche) y se ordena por <code class='ic'>number_of_reviews</code> descendente.</span></div>
</div>

In [111]:
df[(df["municipio"] == "Manhattan") & (df["minimum_nights"] >= 1)]\
  .sort_values("number_of_reviews", ascending=False)\
  .head(3)

,id,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,name,host_id,host_name,municipio,barrio,latitude,longitude,room_type
2031,903972.0,49.0,1.0,607.0,2019-06-21,7.75,3.0,293.0,Great Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82085,-73.94025,Private room
2030,903947.0,49.0,1.0,597.0,2019-06-23,7.72,3.0,342.0,Beautiful Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82124,-73.93838,Private room
2015,891117.0,49.0,1.0,594.0,2019-06-15,7.57,3.0,339.0,Private Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82264,-73.94041,Private room

In [112]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">2</div>
      <div>

        <div class="ex-title">Municipio con precio más bajo y mayor reviews/mes</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Busca el municipio donde el precio promedio sea el más bajo y la cantidad de reviews por mes sea el mayor. ¿Cuáles son las 3 habitaciones que mejor se adaptan?</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Se usa <code class='ic'>.index[0]</code> para obtener el nombre del municipio con menor precio promedio del resultado del <code class='ic'>groupby</code>.</span></div>
</div>

In [113]:
municipio = df.groupby("municipio")[["price", "reviews_per_month"]].mean().sort_values("price").index[0] #Bronx

In [114]:
df[df["municipio"] == municipio].sort_values("reviews_per_month", ascending = False).head(3)

,id,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,name,host_id,host_name,municipio,barrio,latitude,longitude,room_type
23371,18914730.0,95.0,1.0,266.0,2019-06-28,10.34,1.0,345.0,IDEALLY LOCATED COZY COTTAGE,1776707,Luis,Bronx,Throgs Neck,40.83051,-73.82511,Entire home/apt
41945,32595490.0,95.0,2.0,27.0,2019-07-05,8.62,1.0,153.0,Peaceful 2 Bedroom apartment in a private house,245003299,Yoselyn,Bronx,Clason Point,40.80924,-73.85107,Entire home/apt
42252,32801214.0,150.0,1.0,24.0,2019-06-20,8.37,5.0,247.0,TW #6 Private Suite 2nd Fl. 1 to 4 Guests,211136294,Sharon & Erika,Bronx,Schuylerville,40.83560,-73.83369,Private room

In [115]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">3</div>
      <div>

        <div class="ex-title">5 opciones más económicas en Brooklyn/Manhattan</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Quiero rentar un Airbnb completo por un total de 200 días, en Brooklyn o Manhattan; no quiero pagar más de 150 dólares por noche. ¿Cuáles son las 5 opciones más económicas?</p></div>
  </div>

</div>

In [116]:
df[(df["municipio"].isin(["Brooklyn", "Manhattan"])) & (df["price"] <= 150) & (df["availability_365"] >= 200)].sort_values("price").head()

,id,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,name,host_id,host_name,municipio,barrio,latitude,longitude,room_type
25795,20639792.0,0.0,1.0,95.0,2019-06-21,4.37,6.0,232.0,Contemporary bedroom in brownstone with nice view,86327101,Adeyemi,Brooklyn,Bedford-Stuyvesant,40.68279,-73.91170,Private room
25796,20639914.0,0.0,1.0,95.0,2019-06-23,4.35,6.0,222.0,Cozy yet spacious private brownstone bedroom,86327101,Adeyemi,Brooklyn,Bedford-Stuyvesant,40.68258,-73.91284,Private room
26841,21291569.0,0.0,30.0,2.0,2019-06-22,0.11,6.0,333.0,Coliving in Brooklyn! Modern design / Shared room,101970559,Sergii,Brooklyn,Bushwick,40.69211,-73.90670,Shared room
20992,16620607.0,11.0,2.0,113.0,2019-06-22,3.86,1.0,261.0,Spacious and Modern 2 Bedroom Apartment,109725962,Erika,Brooklyn,Bushwick,40.68994,-73.91556,Entire home/apt
46049,35042058.0,11.0,7.0,0.0,NaT,NaN,1.0,273.0,"Big one bedroom apt, new and beautiful.",19342,Rivka,Manhattan,Upper West Side,40.79900,-73.96315,Entire home/apt

In [117]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">4</div>
      <div>

        <div class="ex-title">Habitaciones por municipio y tipo con precio promedio</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ En un nuevo DataFrame muestra por municipio: el número de habitaciones por tipo y el precio promedio de todas las habitaciones por municipio.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Recuerda usar <code class='ic'>'count'</code> y <code class='ic'>'mean'</code> como strings para evitar FutureWarning.</span></div>
</div>

In [118]:
df.groupby(["municipio", "room_type"]).agg({"id"    : ["count"],
                                            "price" : ["mean"]})

                                  id       price
                               count        mean
municipio     room_type
Bronx         Entire home/apt    379  127.506596
              Private room       652   66.788344
              Shared room         60   59.800000
Brooklyn      Entire home/apt   9559  178.327545
              Private room     10132   76.500099
              Shared room        413   50.527845
Manhattan     Entire home/apt  13199  249.239109
              Private room      7982  116.776622
              Shared room        480   88.977083
Queens        Entire home/apt   2096  147.050573
              Private room      3372   71.762456
              Shared room        198   69.020202
Staten Island Entire home/apt    176  173.846591
              Private room       188   62.292553
              Shared room          9   57.444444

In [119]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">5</div>
      <div>

        <div class="ex-title">Crear columna Rating</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Crea una nueva columna con el rating según la fórmula:</p><p class="ex-task">→ Rating = (Puntaje de ciudad) + (número de reviews / 629) + (disponibilidad / 365)</p><p class="ex-task">→ Puntajes: Manhattan=10/10, Brooklyn=8/10, Queens=6/10, Staten Island=4/10, Bronx=2/10</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">La función <code class='ic'>rating()</code> recibe 3 argumentos por fila. Se aplica con <code class='ic'>.apply(lambda x: ..., axis=1)</code> donde <code class='ic'>axis=1</code> indica que opera sobre filas.</span></div>
</div>

In [120]:
def rating(ciudad, review, disp):

    if ciudad == "Manhattan":
        return 10/10 + review/629 + disp/365

    elif ciudad == "Brooklyn":
        return 8/10 + review/629 + disp/365

    elif ciudad == "Queens":
        return 6/10 + review/629 + disp/365

    elif ciudad == "State Island":
        return 4/10 + review/629 + disp/365

    else:
        return 2/10 + review/629 + disp/365

In [121]:
df["rating"] = df.apply(lambda x: rating(x["municipio"], x["number_of_reviews"], x["availability_365"]), axis = 1)

In [123]:
df.head()

,id,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,name,host_id,host_name,municipio,barrio,latitude,longitude,room_type,rating
0,2539.0,149.0,1.0,9.0,2018-10-19,0.21,6.0,365.0,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,1.814308
1,2595.0,225.0,1.0,45.0,2019-05-21,0.38,2.0,355.0,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,2.044145
2,3647.0,150.0,3.0,0.0,NaT,NaN,1.0,365.0,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,2.000000
3,3831.0,89.0,1.0,270.0,2019-07-05,4.64,1.0,194.0,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,1.760760
4,5022.0,80.0,10.0,9.0,2018-11-19,0.10,1.0,0.0,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,1.014308

In [124]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">6</div>
      <div>

        <div class="ex-title">5 habitaciones con mayor rating por municipio</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra las 5 habitaciones de cada municipio con mayor rating.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El patrón <code class='ic'>sort_values().groupby().head(n)</code> es la forma estándar de obtener los top-N por grupo.</span></div>
</div>

In [125]:
df.sort_values(["municipio", "rating"], ascending = False).groupby("municipio").head(5)

,id,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,name,host_id,host_name,municipio,barrio,latitude,longitude,room_type,rating
256,63320.0,36.0,2.0,333.0,2019-07-02,3.19,6.0,340.0,D Private Che@p Room 2 Explore NYC,303939,Lissette,Staten Island,Tompkinsville,40.63481,-74.08519,Private room,1.660919
249,62452.0,36.0,2.0,193.0,2019-06-25,1.85,6.0,360.0,A SpeciaL!! Private Room in NY,303939,Lissette,Staten Island,Tompkinsville,40.63536,-74.08537,Private room,1.493138
251,62787.0,37.0,2.0,177.0,2019-07-02,1.71,6.0,320.0,C Private Room By The Ferry,303939,Lissette,Staten Island,Tompkinsville,40.63518,-74.08546,Private room,1.358111
13046,9882254.0,52.0,2.0,137.0,2019-07-01,3.17,3.0,340.0,Owl's Landing - Garden Room,50068597,Alex,Staten Island,Stapleton,40.63516,-74.07735,Private room,1.349313
18699,14804661.0,125.0,2.0,96.0,2019-07-01,2.82,5.0,362.0,"Cozy 4 beds, Free Ferry to Manhattan.",92493393,Eddie & Lois,Staten Island,West Brighton,40.63333,-74.11311,Entire home/apt,1.344404
11759,9145202.0,47.0,1.0,629.0,2019-07-05,14.58,2.0,333.0,Room near JFK Queen Bed,47621202,Dona,Queens,Jamaica,40.66730,-73.76831,Private room,2.512329
20403,16276632.0,48.0,1.0,510.0,2019-07-06,16.22,5.0,341.0,Cozy Room Family Home LGA Airport NO CLEANING FEE,26432133,Danielle,Queens,East Elmhurst,40.76335,-73.87007,Private room,2.345057
1103,467634.0,39.0,1.0,454.0,2019-06-18,5.27,1.0,353.0,yahmanscrashpads,2321321,Lloyd,Queens,Jamaica,40.67747,-73.76493,Shared room,2.288904
1271,546383.0,55.0,1.0,474.0,2019-05-25,5.53,3.0,332.0,My Little Guest Room in Flushing,2680820,Linda,Queens,Flushing,40.75578,-73.81948,Private room,2.263166
8001,6157276.0,65.0,1.0,466.0,2019-06-22,9.16,4.0,331.0,Bright LARGE BED near Manhattan,23591164,Angela,Queens,East Elmhurst,40.76664,-73.87577,Private room,2.247708
2030,903947.0,49.0,1.0,597.0,2019-06-23,7.72,3.0,342.0,Beautiful Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82124,-73.93838,Private room,2.886112
2015,891117.0,49.0,1.0,594.0,2019-06-15,7.57,3.0,339.0,Private Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82264,-73.94041,Private room,2.873123
2031,903972.0,49.0,1.0,607.0,2019-06-21,7.75,3.0,293.0,Great Bedroom in Manhattan,4734398,Jj,Manhattan,Harlem,40.82085,-73.94025,Private room,2.767764
195,51572.0,123.0,1.0,375.0,2019-06-18,3.52,1.0,328.0,Prime Location in Manhattan,237329,Lee,Manhattan,Chelsea,40.74859,-73.99671,Private room,2.494815
225,58059.0,60.0,1.0,458.0,2019-07-03,4.58,2.0,258.0,PRIVATE Room on Historic Sugar Hill,277379,Agnes,Manhattan,Harlem,40.82510,-73.94287,Private room,2.434989
1547,699472.0,220.0,1.0,404.0,2019-06-25,4.90,2.0,341.0,NYC 1st Shipping Container Home,3587751,Janet-David,Brooklyn,Williamsburg,40.70995,-73.95536,Entire home/apt,2.376536
4870,3474320.0,160.0,1.0,488.0,2019-07-01,8.14,1.0,269.0,Private brownstone studio Brooklyn,12949460,Asa,Brooklyn,Park Slope,40.67926,-73.97711,Entire home/apt,2.312821
4931,3533604.0,96.0,1.0,332.0,2019-07-06,5.57,2.0,355.0,Private Room in a two bedroom apt.,9510645,Rylan,Brooklyn,Bushwick,40.70399,-73.92813,Private room,2.300425
3105,1843108.0,125.0,1.0,319.0,2019-07-08,8.52,1.0,357.0,HappyCozy GuestSuite w/ Great Energy close to JFK,2021121,Megan,Brooklyn,Cypress Hills,40.67840,-73.89362,Entire home/apt,2.285236
1571,713538.0,175.0,1.0,363.0,2019-06-16,4.55,2.0,323.0,Chic Victorian private apartment in townhouse,3672774,Alison,Brooklyn,Clinton Hill,40.68341,-73.96060,Entire home/apt,2.262038
510,182177.0,125.0,2.0,271.0,2019-06-20,2.84,2.0,347.0,A PRIVATE FLAT / APARTMENT- $SPECIAL$,873273,Christian & Carla,Bronx,Allerton,40.86466,-73.85709,Entire home/apt,1.581528
23371,18914730.0,95.0,1.0,266.0,2019-06-28,10.34,1.0,345.0,IDEALLY LOCATED COZY COTTAGE,1776707,Luis,Bronx,Throgs Neck,40.83051,-73.82511,Entire home/apt,1.568099
171,44096.0,40.0,1.0,219.0,2019-07-04,2.04,3.0,353.0,Room with a View,190409,Waundell,Bronx,Highbridge,40.83232,-73.93184,Private room,1.515295
1193,506575.0,45.0,3.0,190.0,2019-06-06,2.21,2.0,329.0,Bronx Room Near Yankees + Harlem,2001830,Jose And Ysaira,Bronx,Morris Heights,40.84937,-73.91328,Private room,1.403437
14310,11138823.0,90.0,2.0,199.0,2019-06-21,5.00,2.0,319.0,A beautiful Cozy 1 BR Apartment.,57885474,Shully'S,Bronx,Wakefield,40.89694,-73.86055,Entire home/apt,1.390348

In [126]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">7</div>
      <div>

        <div class="ex-title">Reviews por municipio y tipo de habitación</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Crea un DataFrame con la cantidad de reviews de cada municipio de acuerdo al tipo de habitación.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">Recuerda usar <code class='ic'>'mean'</code> como string en lugar de <code class='ic'>np.mean</code> para evitar FutureWarning.</span></div>
</div>

In [128]:
df.groupby(["municipio", "room_type"]).agg({"number_of_reviews": ["mean"]})

                              number_of_reviews
                                           mean
municipio     room_type
Bronx         Entire home/apt         30.678100
              Private room            25.018405
              Shared room              7.200000
Brooklyn      Entire home/apt         27.945183
              Private room            21.086952
              Shared room             14.026634
Manhattan     Entire home/apt         17.815516
              Private room            26.202706
              Shared room             21.400000
Queens        Entire home/apt         28.933206
              Private room            27.746441
              Shared room             13.863636
Staten Island Entire home/apt         33.278409
              Private room            30.159574
              Shared room              1.555556

In [129]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">8</div>
      <div>

        <div class="ex-title">10 barrios con mayor precio por habitación individual</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra los 10 barrios con mayor precio por habitación individual.</p></div>
  </div>

</div>

In [130]:
df[df["room_type"] == "Private room"][["barrio", "price"]].sort_values("price", ascending = False).head(10)

                   barrio    price
9151              Astoria  10000.0
12342     Lower East Side   9999.0
45666       East Flatbush   7500.0
37194     Upper West Side   6500.0
4345   Bedford-Stuyvesant   5000.0
43670  Bedford-Stuyvesant   4200.0
28946             Chelsea   3210.0
39846  Financial District   3000.0
946       Upper West Side   3000.0
28727      Brighton Beach   3000.0

In [131]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">9</div>
      <div>

        <div class="ex-title">Barrio con mejor rating por municipio</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Encuentra el barrio con mejor rating de cada municipio.</p></div>
  </div>
  <div class="nb-note"><i class="ti ti-info-circle" style="color:#0F766E;font-size:15px;flex-shrink:0;margin-top:1px;"></i><span class="nb-note-text">El filtro por <code class='ic'>Entire home/apt</code> selecciona solo apartamentos o casas completas, excluyendo habitaciones privadas y compartidas.</span></div>
</div>

In [132]:
#df[df["room_type"] == "Entire home/apt"][["barrio", "price", "municipio", "rating"]].sort_values("price").groupby("municipio").aggregate({"rating" : "max"})


df[df["room_type"] == "Entire home/apt"][["barrio", "price", "municipio", "rating"]].sort_values("rating", ascending = False).groupby("municipio").head(1)

              barrio  price      municipio    rating
929     East Village  189.0      Manhattan  2.393906
1547    Williamsburg  220.0       Brooklyn  2.376536
5816         Jamaica   89.0         Queens  2.143180
510         Allerton  125.0          Bronx  1.581528
18699  West Brighton  125.0  Staten Island  1.344404

In [133]:
# @title
%%html

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
<style>
  @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500&family=DM+Sans:wght@300;400;500;600&display=swap');
  .nb-cell{font-family:'DM Sans',sans-serif;padding:1.2rem 0;max-width:860px;}
  .nb-divider{height:2px;background:linear-gradient(90deg,#1E3A8A 0%,#475569 60%,transparent 100%);margin-bottom:1.1rem;border:none;}
  code.ic{font-family:'Source Code Pro',monospace;font-size:12.5px;background:#EFF6FF;color:#1E3A8A;padding:2px 7px;border-radius:4px;border:1px solid #BFDBFE;white-space:nowrap;}
  .nb-note{display:flex;gap:10px;align-items:flex-start;background:#F0FDF4;border-left:3px solid #0F766E;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .nb-note-text{font-size:13px;color:#0f766e;line-height:1.6;}
  .hint-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .hint-text{font-size:13px;color:#92400E;line-height:1.6;}
  .warn-box{display:flex;align-items:flex-start;gap:10px;background:#FFF7ED;border-left:3px solid #F59E0B;border-radius:0 6px 6px 0;padding:10px 14px;margin-top:.8rem;}
  .warn-text{font-size:13px;color:#92400E;line-height:1.6;}
  .ex-card{border-radius:10px;overflow:hidden;border:1px solid rgba(0,0,0,.08);box-shadow:0 2px 8px rgba(0,0,0,.05);}
  .ex-hdr{display:flex;align-items:center;gap:12px;padding:10px 16px;background:#1E3A8A;}
  .ex-num{display:flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.15);color:#fff;font-size:13px;font-weight:700;flex-shrink:0;}
  .ex-title{font-size:13px;font-weight:600;color:rgba(255,255,255,.95);letter-spacing:.2px;}
  .ex-body{background:#F8FAFF;padding:12px 16px;}
  .ex-task{font-size:13.5px;color:#1e293b;line-height:1.65;margin:0 0 .5rem 0;}
  .ex-task:last-child{margin-bottom:0;}
</style>

<div class="nb-cell">
  <div class="ex-card">
    <div class="ex-hdr">
      <div class="ex-num">10</div>
      <div>

        <div class="ex-title">2 barrios con menor precio por municipio</div>
      </div>
    </div>
    <div class="ex-body"><p class="ex-task">▸ Del resultado anterior, selecciona los 2 barrios con el menor precio por dep/casa completo.</p></div>
  </div>

</div>

In [134]:
df[df["room_type"] == "Entire home/apt"][["barrio", "price", "municipio", "rating"]].sort_values("price", ascending = True).groupby("municipio").head(2)

                   barrio  price      municipio    rating
25778        Williamsburg    0.0       Brooklyn  1.004769
26259         Murray Hill    0.0      Manhattan  1.000000
22835             Jamaica   10.0         Queens  1.358773
35601  Bedford-Stuyvesant   10.0       Brooklyn  0.807949
23256     Upper East Side   10.0      Manhattan  1.015898
33225             Jamaica   10.0         Queens  1.544565
23537           Wakefield   28.0          Bronx  0.200000
42661            Woodlawn   35.0          Bronx  0.368343
46547          St. George   48.0  Staten Island  0.268493
31670       Tompkinsville   48.0  Staten Island  0.201590